export const EVENT_TYPE_MAP = {
	click: {
		type: 'MouseEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'MouseEvent',
		},
	},
	contextmenu: {
		type: 'MouseEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'MouseEvent',
		},
	},
	dblclick: {
		type: 'MouseEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'MouseEvent',
		},
	},
	pointerup: {
		type: 'PointerEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'PointerEvent',
		},
	},
	pointerdown: {
		type: 'PointerEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'PointerEvent',
		},
	},
	pointerover: {
		type: 'PointerEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'PointerEvent',
		},
	},
	pointerout: {
		type: 'PointerEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'PointerEvent',
		},
	},
	pointerenter: {
		type: 'PointerEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'PointerEvent',
		},
	},
	pointerleave: {
		type: 'PointerEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'PointerEvent',
		},
	},
	pointermove: {
		type: 'PointerEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'PointerEvent',
		},
	},
	pointercancel: {
		type: 'PointerEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'PointerEvent',
		},
	},
	wheel: {
		type: 'WheelEvent',
		properties: {
			eventObject: 'THREE.Object3D',
			intersections: 'THREE.Intersection[]',
			unprojectedPoint: 'THREE.Vector3',
			pointer: 'THREE.Vector2',
			delta: 'number',
			ray: 'THREE.Ray',
			camera: 'THREE.Camera',
			stopPropagation: '() => void',
			nativeEvent: 'WheelEvent',
		},
	},
};
